- src/common/modify-settings-modal/index.tsx
- src/home/swap-container/components/swap/index.tsx
- src/hooks/useAllowance.ts
- src/hooks/useBalance.ts
- src/hooks/usePrevious.ts
Avoid "Confirm Operation / Allow" button flickr on position acceptance by correcting useEffect dependencies, memoization and default values
> Avoid unnecesary renders caused by fetching new data

- src/config/constants/swapIntervals.ts
- src/graphql/getAvailablePairs.graphql.ts
- src/graphql/getPairSwaps.graphql.ts
- src/home/current-positions/components/position/index.tsx
- src/home/swap-container/components/step2/index.tsx
- src/home/swap-container/components/swap/index.tsx
- src/position-detail/position-data/index.tsx
- src/services/pairService.ts
- src/types/pairs.ts
- src/types/responses.ts
- src/utils/parsing.ts
This reverts commit 71aadcca3025f735e94b911f3366c98358cb3608.
> Revert "feat(*): add next swap available at on positions (#218)"

- src/services/sdkService.ts
We are default to the public rpc at all times now
> fix: default to public rpc

- package.json
- src/services/sdkService.ts
- yarn.lock
We are now simplifying the sdk service by using the sdk directly
> refactor: simplify sdk service

- src/common/withdraw-modal/index.tsx
- src/graphql/getPosition.graphql.ts
- src/home/current-positions/index.tsx
- src/hooks/useUsdPrice.ts
- src/hooks/useUsdRawPrice.ts
- src/position-detail/frame/index.tsx
- src/position-detail/swaps/components/timeline/index.tsx
- src/state/position-details/reducer.ts
- src/types/positions.ts
- src/types/transactions.ts
- Add yield gains in Timeline summary
- Avoid fetching USD price when amount === 0
Snapshot:
> Add yield gains in summary

- package.json
- src/services/sdkService.ts
- yarn.lock
We are now updating the SDK, which basically adds the new Mean Finance source 🔥
> feat: add mean source

- src/common/components/modify-settings-modal/index.tsx
> fix(modifySettingsModal): hover on authorize allowance button

- src/services/positionService.ts
- With this change:
- All promises, except the last version, will timeout after 30 seconds.
- If a promise times out or encounters an error, it will resolve with { data: null, error: true }.
> feat(positionService): add timeout to legacy subgraphs

- lang/en.json
- lang/es.json
- src/common/components/token-picker/index.tsx
When the user enters an invalid address:
When the user enters a valid address, but no token was found
> fix(token-picker): show error when importing a token

- lang/en.json
- lang/es.json
- src/common/components/claim-modal/index.tsx
- Improved the conditional rendering logic in the ClaimModal component to handle various user scenarios.
- Added handling for the case when the wallet is not connected.
- Ensured that a consistent message is displayed based on the user's information.
> feat(claimModal): add message when there is nothing to claim

- apps/root/package.json
- apps/root/src/services/sdkService.ts
- yarn.lock
We are now updating the SDK to version 0.0.151, which has small breaking change
> chore: update sdk

- apps/root/package.json
- apps/root/src/services/sdkService.ts
- yarn.lock
Wait for the API to be deployed to prod before merging please :)
> feat: updates sdk

- apps/root/src/common/mocks/tokens.ts
- apps/root/src/common/utils/dcaSubgraphApolloClient.ts
- apps/root/src/constants/addresses.ts
- apps/root/src/constants/currency.ts
- apps/root/src/constants/positions.ts
- apps/root/src/constants/yield.ts
- apps/root/src/state/token-lists/reducer.ts
Enables Gnosis Chain on Mean's frontend.
> feat: enables gnosis chain

- apps/root/src/common/components/wallet-selector/index.tsx
- apps/root/src/common/utils/currency.ts
- apps/root/src/constants/routes.tsx
- apps/root/src/frame/components/navigation/index.tsx
- apps/root/src/frame/index.tsx
- apps/root/src/hooks/useCountingAnimation.ts
- apps/root/src/pages/aggregator/frame/index.tsx
- apps/root/src/pages/aggregator/swap-container/components/top-bar/index.tsx
- apps/root/src/pages/dca/create-position/components/step1/index.tsx
- apps/root/src/pages/dca/frame/index.tsx
- apps/root/src/pages/home/components/activity/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/pages/home/frame/index.tsx
- apps/root/src/pages/home/index.tsx
- apps/root/src/pages/transfer/transfer-container/components/transfer-form/index.tsx
- apps/root/src/services/providerService.ts
- apps/root/src/state/index.ts
- packages/ui-library/src/components/index.tsx
- packages/ui-library/src/components/table/Table.stories.tsx
- packages/ui-library/src/components/table/index.tsx
https://github.com/Mean-Finance/dca-fe/assets/144699868/afb488d4-02f4-42dc-837c-2b21bc358df9
> home(*): implement home frame and routing + Portfolio  breakdown

- apps/root/package.json
- yarn.lock
A user reported an issue when making a DCA deposit to Base Goerli. The issue was within the SDK, and now it's fixed
But we need to update to the latest version on the FE
> fix: base goerli deposit

- apps/root/src/common/components/wallet-selector/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/pages/home/frame/index.tsx
- packages/ui-library/src/components/options-menu/index.tsx
- packages/ui-library/src/components/transaction-receipt/TransactionReceipt.stories.tsx
- packages/ui-library/src/components/virtualized-table/index.tsx
- packages/ui-library/src/theme/table-variants.ts
> Apply styles to portfolio breakdown and networth

- apps/root/src/state/transactions/transactionUpdater.tsx
> feat(rootstock): fetch txByHash for effectiveGasPrice on rootstock

- apps/root/src/pages/dca/create-position/components/dca-recap-data/index.tsx
- apps/root/src/pages/dca/create-position/components/swap/index.tsx
> feat(dca): Add recap data when creating position

- apps/root/src/common/components/net-worth/index.tsx
- apps/root/src/common/components/networth-number/index.tsx
- apps/root/src/constants/errorMessages.ts
- apps/root/src/frame/components/navigation/index.tsx
- apps/root/src/frame/components/promises-initializer/index.tsx
- apps/root/src/hooks/useNetWorth.ts
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/pages/home/components/dca-dashboard/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/pages/home/components/widget-frame/index.tsx
- apps/root/src/pages/home/frame/index.tsx
- packages/ui-library/src/components/circularProgressWithBackground/index.tsx
- packages/ui-library/src/components/dashboard/index.tsx
- packages/ui-library/src/components/index.tsx
- packages/ui-library/src/components/virtualized-table/index.tsx
- packages/ui-library/src/icons/arrowUp.tsx
- packages/ui-library/src/icons/index.tsx
- packages/ui-library/src/theme/components.ts
- packages/ui-library/src/theme/variants/table-variants.ts
> feat(home): add dca home widget

- apps/root/lang/en.json
- apps/root/lang/es.json
- apps/root/src/lang/es.json
- apps/root/src/pages/dca/frame/index.tsx
- apps/root/src/pages/position-detail/frame/index.tsx
This reverts commit b8a38c46da9ead0be00f6a7678fc2983985689d4.
> Revert "feat(*): add render down banner (#638)"

- apps/root/src/common/utils/transaction-history/parsing.tsx
- apps/root/src/common/utils/transaction-history/transaction-receipt-parser.tsx
- apps/root/src/hooks/useTransactionsHistory.tsx
- apps/root/src/pages/dca/components/faq/index.tsx
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/pages/transfer/components/recipient-address/components/add-contact-modal/index.tsx
- apps/root/src/pages/transfer/components/recipient-address/components/contact-modal/index.tsx
- packages/ui-library/src/components/transaction-receipt/index.tsx
> feat(txreceipt): Improve receipt styles

- apps/root/src/common/components/claim-modal/components/optimism-campaign/index.tsx
- apps/root/src/common/components/modify-settings-modal/index.tsx
- apps/root/src/common/components/terminate-modal/index.tsx
- apps/root/src/common/components/transaction-modal/index.tsx
- apps/root/src/common/utils/errors.tsx
- apps/root/src/pages/aggregator/swap-container/components/swap/index.tsx
- apps/root/src/pages/dca/create-position/components/swap/index.tsx
- apps/root/src/pages/dca/positions/components/positions-list/current-positions/index.tsx
- apps/root/src/pages/position-detail/components/permissions-container/index.tsx
- apps/root/src/pages/position-detail/components/position-summary-controls/index.tsx
- apps/root/src/pages/position-detail/components/transfer-position-modal/index.tsx
- apps/root/src/pages/transfer/components/confirm-transfer-modal/index.tsx
https://github.com/Mean-Finance/dca-fe/assets/144699868/71e30f69-e51f-441f-922f-84de092ffde7
> fix(transactionModal): handle user rejected transaction

- apps/root/src/common/components/contact-modal/contact-item/index.tsx
- apps/root/src/common/components/wallet-selector/index.tsx
- apps/root/src/hooks/useStoredContactList.ts
- apps/root/src/hooks/useWallets.ts
https://github.com/Mean-Finance/dca-fe/assets/144699868/2112c242-f032-4d4d-a80b-8e13a46e8cfb
> feat(contactList): add wallets as contacts

- apps/root/src/common/components/yield-token-selector/index.tsx
- apps/root/src/pages/dca/create-position/components/step2/components/yield-selector/index.tsx
* fix(mixpanel): do not track yield changes several times
* fixup! fix(mixpanel): do not track yield changes several times
> fix(mixpanel): do not track yield changes several times (#776)

- apps/root/src/common/components/edit-label-modal/index.tsx
https://github.com/Mean-Finance/dca-fe/assets/144699868/3a39c62b-499d-4e69-babe-ee3fb1e1d95c
> fix(walletSelector): improve wallet label edition

- apps/root/src/pages/aggregator/swap-container/components/swap-settings/index.tsx
> fix(aggSettings): show sources popover

- apps/root/src/frame/components/navigation/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/state/config/actions.ts
- apps/root/src/state/config/hooks.ts
- apps/root/src/state/config/reducer.ts
- apps/root/src/state/index.ts
https://github.com/Balmy-protocol/dca-fe/assets/144699868/1c1c1834-7e44-4cf4-960d-7ca32c542c38
> feat(portfolio): hide balances < 1 USD

- apps/root/src/pages/transfer/components/transfer-button/index.tsx
https://github.com/Balmy-protocol/dca-fe/assets/144699868/15be60aa-4ae4-4357-ac23-95c5f3776dd5
> Improve transfer button text

- apps/root/src/common/components/modify-settings-modal/index.tsx
- apps/root/src/common/utils/transaction-history/parsing.tsx
- apps/root/src/hooks/useBuildTransactionMessage.ts
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/pages/home/components/activity/index.tsx
- apps/root/src/services/positionService.spec.ts
- apps/root/src/services/positionService.ts
- packages/common-types/src/accountHistory.ts
- packages/ui-library/src/components/transaction-receipt/index.tsx
> feat(txReceipt): modify position receipt

- apps/root/src/common/mocks/earn.ts
- apps/root/src/pages/earn/components/all-strategies-table/index.tsx
- packages/common-types/src/earn.ts
> feat(earn): add guardian to all strategies table

- apps/root/src/constants/addresses.ts
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/services/accountService.ts
- apps/root/src/services/meanApiService.ts
- apps/root/src/state/balances/actions.ts
* fix(balances): update endpoints
* better network list for balances
> fix(balances): update endpoints (#867)

- apps/root/src/common/mocks/earn.ts
- apps/root/src/pages/earn/components/all-strategies-table/components/filters/index.tsx
- packages/ui-library/src/theme/components.ts
https://github.com/Balmy-protocol/dca-fe/assets/144699868/a700d7bf-b3a5-4387-82e9-7b09ae4263a2
> fix(earn): popover positioning

- apps/root/src/pages/position-detail/components/transfer-position-modal/index.tsx
- apps/root/src/services/positionService.spec.ts
- apps/root/src/services/positionService.ts
- apps/root/src/state/position-details/reducer.ts
https://github.com/Balmy-protocol/dca-fe/assets/144699868/aa688aa8-161d-4150-acc4-2f308add034b
> fix(dca): transfering position to owned wallet

- apps/root/src/common/utils/earn/search.ts
- apps/root/src/hooks/earn/useAllStrategies.ts
- apps/root/src/hooks/earn/useFilteredStrategies.ts
- apps/root/src/pages/earn/components/all-strategies-table/components/filters/index.tsx
- apps/root/src/pages/earn/components/all-strategies-table/components/toolbar/index.tsx
- apps/root/src/pages/earn/components/all-strategies-table/index.tsx
- apps/root/src/services/earnService.ts
- apps/root/src/state/all-strategies-filters/actions.ts
- apps/root/src/state/all-strategies-filters/reducer.ts
- packages/ui-library/src/components/table-pagination/index.tsx
- packages/ui-library/src/theme/variants/input-base-variants.ts
https://github.com/Balmy-protocol/dca-fe/assets/144699868/faa04cc1-8f0b-4f90-96f8-3f96e497cef2
> feat(earn): search for all strategies table

- apps/root/src/common/components/transaction-steps/index.tsx
> fix(transactionSteps): special label for Unlimited approval

- apps/root/src/common/components/net-worth/index.tsx
- apps/root/src/common/components/networth-number/index.tsx
- apps/root/src/common/utils/currency.ts
- apps/root/src/hooks/earn/useUserStrategiesFinancial.ts
- apps/root/src/pages/home/components/widget-frame/index.tsx
- apps/root/src/pages/position-detail/components/summary-container/components/position-data/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/expected-returns/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/financial-data/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/financial-overview/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/index.tsx
- apps/root/src/services/earnService.ts
- packages/ui-library/src/components/breakpoint/index.tsx
- packages/ui-library/src/components/mui-select/index.tsx
- packages/ui-library/src/components/table-pagination/index.tsx
- packages/ui-library/src/components/virtualized-table/index.tsx
> feat(earn): vault summary details - financial data

- apps/root/src/common/utils/transaction-history/index.ts
- apps/root/src/muiTheme.d.ts
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/pages/token-profile/historical-prices/components/custom-dot/index.tsx
- apps/root/src/pages/token-profile/historical-prices/components/graph-tooltip/index.tsx
- apps/root/src/pages/token-profile/historical-prices/index.tsx
- packages/ui-library/src/muitheme.d.ts
- packages/ui-library/src/theme/typography.ts
> feat(token-profile): Add user events to price chart

- apps/root/src/hooks/useUserHasEarnPositions.ts
- apps/root/src/pages/home/components/dca-dashboard/index.tsx
- apps/root/src/pages/home/components/earn-positions-dashboard/index.tsx
- apps/root/src/pages/home/frame/index.tsx
> feat(earn): home widget

- apps/root/src/common/components/form-wallet-selector/index.tsx
- apps/root/src/common/components/network-selector/index.tsx
- apps/root/src/common/components/token-selector/index.tsx
- apps/root/src/pages/aggregator/swap-container/components/step1/index.tsx
- apps/root/src/pages/aggregator/swap-container/index.tsx
- apps/root/src/pages/dca/create-position/components/step1/index.tsx
- apps/root/src/pages/dca/frame/index.tsx
- apps/root/src/pages/earn/home/components/wizard/components/wizard-selection/index.tsx
- apps/root/src/pages/home/components/activity/index.tsx
- apps/root/src/pages/transfer/components/transfer-form/index.tsx
- apps/root/src/pages/transfer/frame/index.tsx
- apps/root/src/state/balances/hooks.ts
- packages/ui-library/src/components/select/index.tsx
- packages/ui-library/src/components/token-picker/index.tsx
- packages/ui-library/src/theme/variants/chip-variants.ts
> feat(wallet-selector): move into form

- apps/root/src/common/components/composed-token-icon/index.tsx
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/services/transactionService.spec.ts
- apps/root/src/services/transactionService.ts
- packages/common-types/src/accountHistory.ts
- packages/common-types/src/responses.ts
> fix(token-profile): Indexing

- packages/ui-library/src/theme/variants/table-variants.ts
> fix(home): portfolio table border fixes

- apps/root/src/frame/index.tsx
https://github.com/user-attachments/assets/9d59c5ed-e099-40eb-993c-5faab5b00996
> fix(*): adjust max-widths

- apps/root/src/common/components/transaction-steps/index.tsx
- apps/root/src/pages/aggregator/swap-container/components/swap/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/components/expected-returns-changes-summary/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/deposit/recap-data/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/deposit/tx-steps/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/changes-summary/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/recap-data/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/tx-steps/index.tsx
- packages/ui-library/src/components/backcontrol/BackControl.stories.tsx
- packages/ui-library/src/components/backcontrol/index.tsx
- packages/ui-library/src/theme/typography.ts
> fix(tx-steps): conform to figma

- apps/root/src/common/mocks/tokens.ts
- apps/root/src/constants/addresses.ts
- apps/root/src/constants/currency.ts
- apps/root/src/constants/positions.ts
- apps/root/src/constants/yield.ts
Reverts Balmy-protocol/dca-fe#1098
> Revert "feat(base): add dca network on base"

- apps/root/src/common/mocks/tokens.ts
- apps/root/src/constants/addresses.ts
- apps/root/src/constants/currency.ts
- apps/root/src/constants/positions.ts
- apps/root/src/constants/yield.ts
Reverts Balmy-protocol/dca-fe#1106
> Revert "Revert "feat(base): add dca network on base""

- apps/root/src/pages/earn/components/strategies-display-wrapper/index.tsx
- apps/root/src/pages/earn/components/strategies-list/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/empty-portfolio/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/filters/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/toolbar/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/total-footer/index.tsx
- apps/root/src/pages/earn/components/strategies-table/index.tsx
- apps/root/src/pages/earn/home/components/all-strategies-table/index.tsx
- apps/root/src/pages/earn/portfolio/components/earn-positions-table/index.tsx
- apps/root/src/pages/earn/portfolio/components/financial-data/index.tsx
- apps/root/src/pages/earn/portfolio/components/tvl-graph/index.tsx
- apps/root/src/pages/earn/portfolio/frame/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/expected-returns/index.tsx
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/financial-overview/index.tsx
- packages/ui-library/src/components/graph-container/index.tsx
- packages/ui-library/src/components/table/index.tsx
- packages/ui-library/src/theme/pallete.ts
> fix(earn): empty state + avoid table pagination for Portfolio

- apps/root/src/common/components/transaction-confirmation/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/columns/index.tsx
- apps/root/src/pages/earn/components/strategies-table/components/total-footer/index.tsx
> fix: plus sign and swap receipt order

- apps/root/src/common/utils/parsing.ts
- apps/root/src/muiTheme.d.ts
- apps/root/src/pages/strategy-guardian-detail/investment-data/components/balances/index.tsx
- apps/root/src/pages/strategy-guardian-detail/vault-data/components/data-about/index.tsx
- apps/root/src/pages/strategy-guardian-detail/vault-data/components/data-rewards/index.tsx
- apps/root/src/pages/strategy-guardian-detail/vault-data/index.tsx
- packages/ui-library/src/assets/index.tsx
- packages/ui-library/src/assets/rain-coins/index.tsx
- packages/ui-library/src/muitheme.d.ts
- packages/ui-library/src/theme/pallete.ts
> feat(earn): balances and rewards info improvements

- apps/root/src/services/permit2Service.ts
- apps/root/src/services/positionService.spec.ts
- apps/root/src/services/positionService.ts
- apps/root/src/services/providerService.ts
- apps/root/src/services/walletService.spec.ts
- apps/root/src/services/walletService.ts
> fix(*): always ask for chain change when submitting a wallet request

- apps/root/src/pages/strategy-guardian-detail/strategy-management/deposit/hooks/useEarnDepositActions.tsx
https://github.com/user-attachments/assets/c2076e2f-7296-4874-b8b6-68bca18675d5
> fix(earn): reorder tx steps for create position

- apps/root/src/frame/index.tsx
Reverts Balmy-protocol/dca-fe#1337
> Revert "chore(*): add downtime modal for database reset"

- apps/root/src/common/components/news-banners/donut-banner/index.tsx
- apps/root/src/pages/home/frame/index.tsx
- apps/root/src/state/balances/hooks.ts
- packages/ui-library/src/assets/galxe.tsx
- packages/ui-library/src/assets/index.tsx
> feat(news-banner): earn galxe quest

- apps/root/src/common/components/news-banners/lm-earn-banner/index.tsx
> feat(news-banner): gnosis banner for earn
