Balmy-protocol/dca-fe

- src/common/token-input/index.tsx
When using the protocol token, we were miscalculating the "half" value
> fix: use correct half value

- src/services/positionService.ts
`TRANSACTION_TYPES.NEW_POSITION` was missing a `"v"` char in the id, so then on `src/services/positionService.ts:160` we failed to get the position and update it with data from the positions api call, hence creating a new position that appeared as duplicate until we refreshed the client.
> fix: add v char before version

- src/common/modify-settings-modal/index.tsx
The check `position.user === walletService.getAccount()` failed because `walletService.getAccount()` had uppercases while `position.user` didn't, so we were never shown the "Approve" button in the position edition modal.
> fix check by using lowecase

- package.json
- src/services/sdkService.ts
- yarn.lock
We are now making two changes:
1. We are updating the SDK to the newest version, which has some bug fixes
2. We are now using 0x from the API, since we now have an API key, which allows for some more rate limiting
> chore: update sdk to 0.0.36

- package.json
- src/services/sdkService.ts
- yarn.lock
We are now:
- Updating the SDK to the latest version
- Using Odos locally, instead of going to the API
> chore: update sdk and use odos locally

- src/services/sdkService.ts
We are doing two things here:
1. We are adding Mean's price source as part of the sources that will be queried. This is because Defi Llama supports some 4626 tokens, but they are updated once every hour. So we need something that has more up-to-date prices
2. We are adding a small 1 min cache. Since users could perform various quotes for the same pair in a small time windows, we want to avoid rate limiting issues (specially with Coingecko), so we can cache them. The cache will hold up to 20 token prices, so it should have no impact on memory
> refactor: add mean price source

- src/pages/aggregator/swap-container/components/swap-button/index.tsx
Url was being reseted to `mean.finance/swap/chainId` before triggering a `window.location.reload()`, so selected tokens were lost.
The `chainId` param is already being updated in the URL by the network selector component.
1. Enter to the Aggregator page and connect with a wallet that is not a `CHAIN_CHANGING_WALLETS_WITHOUT_REFRESH`
2. Change network using the Network Selector & select tokens to perform a swap
3. Click on the button 'Change network to XXXXX'
Site should refresh and selected tokens should persists.
> fix(aggregator): Loosing tokens after network switch

- src/pages/aggregator/swap-container/components/from-amount-input/index.tsx
We were only showing MAX balance (in the from token) if the `chainId` selected by the user in the UI (the one stored by redux) is the same as the one active in the user's wallet
With this change, that validation is not being performed anymore, allowing the user to see it's MAX balance despite of the chain that is active in the wallet.
Using `CHAIN_CHANGING_WALLETS_WITHOUT_REFRESH` (e.g. Rabby)
Using refreshing wallets (e.g. Metamask)
> fix(aggregator): show MAX balance even when connected to other chains

- src/pages/dca/positions/components/current-positions/index.tsx
When a user attempted to withdraw a token, the modal displayed ETH or WETH instead of the actual protocol token. 
This happened because of an incorrect currentNetwork value, which was always the mainnet. Now the currentNetwork value matches the one in use by the user.
Expected behaviour
Current behaviour
> fix(current-positions): Wrong token name displayed on withdraw modal

- src/common/utils/quotes.ts
- src/services/aggregatorService.ts
- src/services/web3Service.ts
- src/types/aggregator.ts
From now on, we will be tracking failed quotes in MixPanel, including the error type and the `sourceTimeout` selected by the user. 
_Below are the different types of errors and an example of each as received by the application._
- Timeout: These errors occur when a request times out.
> Request to https://api.mean.finance/v1/swap/networks/42220/quotes/0x timeouted at 3.5s
- ReferralCode: Errors related to invalid or unregistered referral codes.
> Example: Odos: failed to calculate a quote between 0xeeeeee…ail\\":\\"Invalid or unregistered referral code\\"}"
- BigIntConversion: Errors arising from attempts to convert an undefined value to a BigInt.
> Example: Cannot convert undefined to a BigInt
- NetworkRequest: General network request failures.
> Example: Network request failed
> feat(aggregator): start tracking failed quotes

- src/constants/addresses.ts
- src/services/priceService.spec.ts
- src/services/priceService.ts
- src/services/web3Service.ts
- Replaced a local API call with SDK integration in the `getUsdHistoricPrice` method.
- Gave `getPriceForGraph` a bit of a refactor for better clarity.
- Introduced unit tests for both `getUsdHistoricPrice` and `getPriceForGraph` methods.
- Added a new method to handle token addresses that are being phased out in favor of native addresses, such as the transition from Bridged USDC (USDC.e) to native USDC.
With these changes, we've resolved the issues with broken graphs. Previously failing URL http://localhost:3000/42161/positions/4/32274 is now functioning as expected.
> fix(priceService): replace api call with sdk implementation + detect outdated token addresses for fetching

- apps/root/src/constants/common.ts
We will be testing $STAR on staging, so we need to add it to the unallowed list on frontend 😊
> chore: adds star to blacklist

- apps/root/package.json
- apps/root/src/services/sdkService.ts
- yarn.lock
We are now update the SDK to include [this](https://github.com/Mean-Finance/sdk/commit/7c48e1e664abee0b381f2b6d712a59f45614002f) change. 
Now, when we estimate buy orders with sell orders, we take slippage into account. While this approach might not work 100% of the times, it should work far better than the current approach
> chore: update sdk to improve buy orders

- apps/root/package.json
- apps/root/src/services/sdkService.ts
- yarn.lock
By updating the SDK, we enable Braindex aggregator for Moonriver, and we also deprecate `portals-fi` which has been deprecated already by the SDK. Tested on my local env, and working sweet.
> chore: updates sdk

- apps/root/src/pages/aggregator/swap-container/components/quote-picker/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/pages/transfer/components/recipient-address/components/contacts-button/index.tsx
- apps/root/src/state/balances/reducer.ts
- apps/root/src/state/index.ts
- packages/ui-library/src/components/container-box/index.tsx
- packages/ui-library/src/components/foreground-paper/index.tsx
- packages/ui-library/src/components/token-picker/index.tsx
- packages/ui-library/src/components/virtualized-table/index.tsx
- packages/ui-library/src/theme/components.ts
Fixed:
- No wallet connected on `<NetWorth />` and `<Portfolio />`
- Re-order styles on ContainerBox to enable Skeletons in `<Portfolio />` render as they should
- Elevation for our Virtualized Tables in order to match design 
- Set border-radius value for ForegroundPaper as default, based on main components (such as `Activity`)
> feat(home): No wallet connected case

- packages/ui-library/src/components/container-box/index.tsx
Having a default value for FlexGrow was always overriding flex shorthand value. This prop default value should be given by flex: default value (already specified as 0 from flex: 0 1 auto)
> fix(ContainerBox): Remove flexGrow default value

- apps/root/package.json
- yarn.lock
We realized that some gas sources were returning invalid properties, so we added a way to filter them out here:
https://github.com/Mean-Finance/sdk/compare/1b99670d2f2debff721200c441da98d9b29f3dac...5abbb6132bb7d6c0ff851c7e615f3541d080586b
> fix: update sdk to fix gas service

- apps/root/src/pages/aggregator/swap-container/components/swap/index.tsx
- apps/root/src/pages/dca/create-position/components/swap/index.tsx
- apps/root/src/pages/transfer/components/transfer-form/index.tsx
- packages/ui-library/src/components/transaction-confirmation/index.tsx
> feat(dca): Transaction confirmation

- apps/root/src/common/components/composed-token-icon/index.tsx
- apps/root/src/common/components/token-icon-with-network/index.tsx
It also fixes the "assets" icons that had the same issue. No icon uses borders in general on the design, so I guess this will not break anything.
> fix(composed-token-icon): token and network icon borders

- apps/root/src/pages/home/components/portfolio/index.tsx
While doing BLY-1980, I also detected that:
- There was a loading skeleton missing
- Thickness could look more similar to Figma's
- Also, if the screen loaded slow enough (set network to throttle) the percentage could show 'NaN' as value, added that to the logic of showing / not showing the value.
Prev
New
> fix(portfolio): skeleton missing, column order and thickness

- apps/root/src/common/utils/transaction-history/parsing.tsx
> fix(history): decimal parsing error when parsing api events

- apps/root/src/pages/aggregator/swap-container/components/swap/index.tsx
- packages/ui-library/src/components/transaction-confirmation/index.tsx
Previous behaviour:
Current behaviour:
> fix(txConfirmation): too much decimals for swap

- apps/root/.template.env
- apps/root/README.md
- apps/root/src/common/components/error-boundary/indext.tsx
- apps/root/src/common/utils/errors.tsx
- apps/root/src/frame/components/footer/components/balmy-logo/index.tsx
- apps/root/src/frame/components/footer/index.tsx
- apps/root/src/frame/components/navigation/index.tsx
- apps/root/src/pages/dca/components/low-liquidity-modal/index.tsx
- apps/root/src/pages/dca/positions/components/positions-list/position-card/components/position-warning/index.tsx
- packages/ui-library/src/components/navigation/index.tsx
Only references that are still waiting to be changed (since we do not know the exact urls):
- Link to audits
- Link to token list with new github repo name
- Link to github
Basically, everything that references the github. 
Additionally removed the FAQ since we don't have any place to link it too, at least yet 🫤
> fix: changes references and links from mean to balmy

- apps/root/src/common/components/address-input/index.tsx
- apps/root/src/common/components/contact-modal/index.tsx
- apps/root/src/hooks/useStoredContactList.ts
- apps/root/src/hooks/useValidateAddress.ts
- apps/root/src/pages/transfer/components/recipient-address/index.tsx
- apps/root/src/pages/transfer/components/transfer-button/index.tsx
- apps/root/src/pages/transfer/components/transfer-form/index.tsx
With this change:
- Contact as recipient is being recognized
- Active wallet does not appear as contact
- Clicking a contact is validated as same as typing the address (handy when active wallet is changed, after the contact is selected)
- Url param is now being validated too
> fix(transfer): validate recipient in edge cases

- apps/root/src/state/balances/balancesUpdater.tsx
- apps/root/src/state/balances/reducer.ts
We were displaying a blacklist token (legacyERC20ETH) in OP.
Also, we were storing all tokens in balances redux store, no matter if balance = 0 (performance improvement)
> fix(portfolio): double eth for optimism

- apps/root/src/pages/history/components/historyTable/index.tsx
- packages/ui-library/src/theme/variants/table-variants.ts
> fix(historyTable): improve and generalize table styles

- apps/root/src/frame/index.tsx
- apps/root/src/hooks/useDcaTokens.ts
- apps/root/src/services/pairService.ts
In the constructor of the `pairService` class, the `setTimeout` was delayed to allow React to load. React loaded so quickly that the query wasn't able to load in time. This issue was only reproducible for me in the production environment due to the high performance.
I have prevented this potential issue and moved this logic to a more standardized block.
> fix(dca): better handling for fetching allowed pairs

- apps/root/src/pages/dca/positions/components/positions-list/current-positions/components/position-card-button/index.tsx
> fix(dca): set pending tx color to primary

- apps/root/src/common/components/net-worth/index.tsx
- apps/root/src/common/components/networth-number/index.tsx
- apps/root/src/constants/routes.tsx
- apps/root/src/hooks/useNetWorth.ts
- apps/root/src/pages/history/components/historyTable/index.tsx
- apps/root/src/pages/home/components/activity/index.tsx
- apps/root/src/pages/home/components/portfolio/index.tsx
- apps/root/src/pages/home/components/widget-frame/index.tsx
- apps/root/src/pages/position-detail/components/summary-container/components/position-data/index.tsx
- apps/root/src/pages/token-profile/balance-table/index.tsx
- apps/root/src/pages/token-profile/frame/index.tsx
- apps/root/src/pages/token-profile/header/index.tsx
- apps/root/src/pages/token-profile/historical-prices/index.tsx
- apps/root/src/pages/token-profile/market-stats/index.tsx
- apps/root/src/pages/token-profile/token-distribution/index.tsx
- packages/ui-library/src/components/virtualized-table/index.tsx
- packages/ui-library/src/icons/animated-chevron-right.tsx
Created and added to **`BLY-2954`**:
> fix(token-profile): feedback fixes

- apps/root/src/common/utils/earn/parsing.tsx
- apps/root/src/pages/strategy-guardian-detail/frame/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/asset-input/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/cta-button/index.tsx
- apps/root/src/pages/strategy-guardian-detail/strategy-management/withdraw/hooks/useEarnWithdrawActions.tsx
- apps/root/src/services/earnService.ts
- packages/ui-library/src/components/token-amount-usd-input/index.tsx
- [BLY-3249](https://linear.app/balmy/issue/BLY-3249/no-se-marcan-cambios-en-el-resumen-al-hacer-withdraw
)
- [BLY-3248](https://linear.app/balmy/issue/BLY-3248/ocultar-checkbox-withdraw-rewards-si-no-hay-rewards
)
- [BLY-3282](https://linear.app/balmy/issue/BLY-3282/earn-form-state-persists-across-al-strategies-with-different-tokens
)
- [BLY-3253](https://linear.app/balmy/issue/BLY-3253/problemas-al-retirar-rewards-y-calculo-de-returns-roto)
> fix(earn): review withdraw flow

- apps/root/src/services/earnService.ts
- apps/root/src/services/meanApiService.ts
The signature based manager actually expected the received `bytes` to be an encoded version of `(bytes signature, uint deadline)`. We were only sending the signature, so we now need to fix this
> fix: encode signature bytes correctly

- apps/root/src/common/components/transaction-confirmation/index.tsx
- apps/root/src/common/utils/transactions.spec.ts
- apps/root/src/common/utils/transactions.ts
- apps/root/src/constants/transactions.ts
- apps/root/src/state/balances/hooks.ts
- apps/root/src/state/transactions/transactionUpdater.tsx
- packages/ui-library/src/components/transaction-confirmation/index.tsx
This update improves transaction handling for users leveraging Rabby’s gas account feature. When a Rabby wallet is detected and the current ETH balance is insufficient to cover gas fees, we assume that the user intends to use the gas account functionality. 
In these cases, we extend the transaction confirmation period to three times the usual duration to account for the additional delay incurred while waiting for the gas top-up. Additionally, for transactions involving native tokens (such as ETH transfers), the required gas is now validated against the user’s current balance before processing.
> fix(*): transaction confirmation when using rabby gas account

- apps/root/src/frame/index.tsx
RainbowKit uses a Wagmi hook called `useEns`, which is built into the `RainbowKitProvider`. Wagmi hooks usually rely on the `@tanstack/react-query` package to refetch and cache data. Even though I tried, I couldn’t stop the `useEns` call from happening every time a user connects their wallet to the page. However, since we don’t use Wagmi hooks at all, applying some minimization of TanStack usage (reducing retries and refetches) allowed us to achieve significant performance improvements.
Requests before:
Request after:
Useful docs:
- How to config tanstack [TanStack Query Documentation](https://tanstack.com/query/latest/docs/framework/react/reference/useQuery#usequery)
- Wagmi hook in Rainbow: [RainbowKit GitHub Source](https://github.com/rainbow-me/rainbowkit/blob/ed13be55111b6d16c229ff2e7 …
> fix(*): rainbow kit optimization
